---
channel: edge
addons:
  caddy-2:
    repository: einschmidt/addon-caddy-2
    target: caddy-2
    image: ghcr.io/einschmidt/caddy-2/{arch}
  yarr:
    repository: einschmidt/addon-yarr
    target: yarr
    image: ghcr.io/einschmidt/yarr/{arch}
  youtube-dl:
    repository: einschmidt/addon-youtube-dl
    target: youtube-dl
    image: ghcr.io/einschmidt/youtube-dl/{arch}
  matrix:
    repository: einschmidt/addon-matrix
    target: matrix
    image: ghcr.io/einschmidt/matrix/{arch}
  freshrss:
    repository: einschmidt/addon-freshrss
    target: freshrss
    image: ghcr.io/einschmidt/freshrss/{arch}
  pocket-id:
    repository: einschmidt/addon-pocket-id
    target: pocket-id
    image: ghcr.io/einschmidt/pocket-id/{arch}
  authelia:
    repository: einschmidt/addon-authelia
    target: authelia
    image: ghcr.io/einschmidt/authelia/{arch}
