---
channel: edge
addons:
  caddy-2:
    repository: einschmidt/addon-caddy-2
    target: caddy-2
    image: ghcr.io/einschmidt/caddy-2/{arch}
  yarr:
    repository: einschmidt/app-yarr
    target: yarr
    image: ghcr.io/einschmidt/yarr
  youtube-dl:
    repository: einschmidt/addon-youtube-dl
    target: youtube-dl
    image: ghcr.io/einschmidt/youtube-dl/{arch}
  matrix:
    repository: einschmidt/addon-matrix
    target: matrix
    image: ghcr.io/einschmidt/matrix/{arch}
  freshrss:
    repository: einschmidt/app-freshrss
    target: freshrss
    image: ghcr.io/einschmidt/freshrss
  pocket-id:
    repository: einschmidt/app-pocket-id
    target: pocket-id
    image: ghcr.io/einschmidt/pocket-id
  authelia:
    repository: einschmidt/app-authelia
    target: authelia
    image: ghcr.io/einschmidt/authelia
  fusion:
    repository: einschmidt/app-fusion
    target: fusion
    image: ghcr.io/einschmidt/fusion
  lldap:
    repository: einschmidt/app-lldap
    target: lldap
    image: ghcr.io/einschmidt/lldap
