name: Authelia
version: 2ce3e27
slug: authelia
description: Authelia - Authentication and Authorization Server
url: https://github.com/einschmidt/addon-authelia
arch:
- amd64
- aarch64
init: false
ports:
  9091/tcp: 9091
ports_description:
  9091/tcp: Authelia Web UI and API
map:
- addon_config:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warn|error)
image: ghcr.io/einschmidt/authelia/{arch}
