name: Caddy 2
version: 1.5.4
slug: caddy-2
description: Open source web and proxy server with automatic HTTPS
url: https://github.com/einschmidt/addon-caddy-2
arch:
- armhf
- armv7
- amd64
- aarch64
startup: services
map:
- share:rw
- config
- ssl:rw
host_network: true
options:
  non_caddyfile_config:
    email: your@email.com
    domain: mydomain.com
    destination: localhost
    port: 8123
  args: []
  env_vars: []
  log_level: info
schema:
  non_caddyfile_config:
    email: email?
    domain: str?
    destination: str?
    port: port?
  caddy_upgrade: bool?
  caddy_fmt: bool?
  config_path: str?
  custom_binary_path: str?
  args:
  - str
  env_vars:
  - name: str
    value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
environment:
  LOG_FORMAT: '{LEVEL}: {MESSAGE}'
init: false
image: ghcr.io/einschmidt/caddy-2/{arch}
