---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]

jobs:
  workflows:
    uses: einschmidt/workflows/.github/workflows/repository-updater.yaml@main
    secrets:
      UPDATER_TOKEN: ${{ secrets.UPDATER_TOKEN }}
